<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text21_text21</name>
   <tag></tag>
   <elementGuidId>fde4e2dc-75b8-49a6-807a-4b31cc579e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff977123-6a6d-4c42-9b30-32ce9e8727a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7fc10a4-60f2-4395-9941-e534a0a7620e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text21</value>
      <webElementGuid>571aa492-18d9-4044-93f5-f52ce15e255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text21&quot;)</value>
      <webElementGuid>42097b60-21b6-476f-809a-8dcb9838fb89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text21']</value>
      <webElementGuid>603548c2-7895-432c-bf86-5ff663dcf0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[21]</value>
      <webElementGuid>cf2c50fc-db67-40a9-8501-329d243bad4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text21']</value>
      <webElementGuid>a40194be-c183-4024-bc27-e205a3d8f172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
