<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text37_text37</name>
   <tag></tag>
   <elementGuidId>a877ac84-c1d1-4b80-84a8-cbe0db6a7c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text37</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text37']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18eb3b82-abd5-48d5-8974-7655d1116dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9211f082-c559-44a3-91eb-495e08efc513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text37</value>
      <webElementGuid>96864231-2232-4dc7-acc0-351c5ce2559b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text37&quot;)</value>
      <webElementGuid>41a86366-b9ef-489f-979f-011f1a332de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text37']</value>
      <webElementGuid>fa10fc05-2a0c-410c-8358-c87e5992ec57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[37]</value>
      <webElementGuid>6e4ebc3e-f5f4-4206-86d0-5956a985d320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text37']</value>
      <webElementGuid>be90a0a2-5be6-4572-bed4-4fa6cc69adbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
