<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text27_text27</name>
   <tag></tag>
   <elementGuidId>f763e2b5-f653-4033-a61c-4c8dd943de63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94665ccc-0d3e-47dc-b607-9bf51421ea45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c287fb40-97ad-406d-b406-522672400adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text27</value>
      <webElementGuid>86372b61-c645-4ab8-9a2c-1d35c1ea6c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text27&quot;)</value>
      <webElementGuid>40ff0173-9973-4a22-8f8d-62baf2e2528b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text27']</value>
      <webElementGuid>93cc4862-30eb-46f5-b30a-1d73dd048e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>e74d9778-6070-4d8d-95c3-c824a9626e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text27']</value>
      <webElementGuid>f3385565-e3af-4d72-a723-b8e76b407a82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
