<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text28_text28</name>
   <tag></tag>
   <elementGuidId>82d05d29-17f3-4676-bdd2-dc033dab2885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text28</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text28']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68e0aadc-9aa7-4ab4-9872-bfa8c4cc2a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c461eba5-77df-418b-9b93-e3b48a4ff4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text28</value>
      <webElementGuid>2c4d554d-0fb8-47cb-a8d2-bbe0e4e76eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text28&quot;)</value>
      <webElementGuid>2110a25b-e1f2-4d29-8974-063d60ea6b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text28']</value>
      <webElementGuid>64434194-b511-4e21-a97b-2e28f25bebbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[28]</value>
      <webElementGuid>b2c204b8-822e-4d53-b9a3-04585c2eef54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text28']</value>
      <webElementGuid>fcb8c452-b3f0-48fe-8add-a70783fb4b3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
