<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text7_text7</name>
   <tag></tag>
   <elementGuidId>fc57304b-78db-49f9-bf58-078fd7f02a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5931b621-c206-46a0-9f66-cb6a0888ffe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a389c48a-75f2-4637-aff3-7edb249b9962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text7</value>
      <webElementGuid>01d0debe-0465-49be-be87-cbdce9b55124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text7&quot;)</value>
      <webElementGuid>c86ab8bd-a3cf-4bfa-a29d-29698da9d3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text7']</value>
      <webElementGuid>176b0fc9-c99c-4e06-90ae-52308589a0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>e839fcb9-0c81-44b9-bbe7-c20f763acd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text7']</value>
      <webElementGuid>853b3765-1111-43ba-a614-f17d8405692e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
