<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text9_text9</name>
   <tag></tag>
   <elementGuidId>e95c4999-dc6d-4c78-bff8-0e035b3a5959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c18a3519-33f8-452a-9a2d-768009e3efc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74d3cb7d-3d8f-43a3-af85-c5587e6da2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text9</value>
      <webElementGuid>859cb15e-bd66-413f-9ce9-ebf960043048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text9&quot;)</value>
      <webElementGuid>134220d4-9b05-422a-8bd0-7ab13b89c1b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text9']</value>
      <webElementGuid>343d5181-55ac-461d-b469-287070c6d963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>937ef133-8182-4dca-8936-9aa8fe543c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text9']</value>
      <webElementGuid>e9728a8b-786c-446a-bc21-06b9bdd410f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
