<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text39_text39</name>
   <tag></tag>
   <elementGuidId>8ae3065b-324d-4e15-afb7-293b60d322dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text39</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text39']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a98d953-07ea-4a99-bcee-e842a8b04b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aeda682c-b289-4d6d-b787-1ac766c2a0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text39</value>
      <webElementGuid>44662133-1e30-4cf6-b2c1-a2f6611827b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text39&quot;)</value>
      <webElementGuid>8a19507e-323f-4f33-b0b6-43ee1e8bcf2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text39']</value>
      <webElementGuid>58351b11-3b3e-4c30-a8c1-6c903d949102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[39]</value>
      <webElementGuid>1d147c74-7389-40f8-ab85-4f9fb384f209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text39']</value>
      <webElementGuid>06d964a7-4c78-45a3-b722-2676142a71cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
