<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio4_radio5</name>
   <tag></tag>
   <elementGuidId>34e43efa-2ed8-4556-8f57-2367a15f3a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4725e868-3a1e-470b-a884-8e8879a3ee8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cb4a9bd3-9610-447f-9c9f-c985e50d6788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio5</value>
      <webElementGuid>59cc8514-6e8a-4c92-a0c7-eb8bd74a332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio5</value>
      <webElementGuid>770b7b5c-6972-47c6-a8d4-a7cf358d3472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio5&quot;)</value>
      <webElementGuid>f239133f-585c-4273-ae41-c253488dd907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio5']</value>
      <webElementGuid>fd37e725-7e8d-4fc9-8c69-6f0488db05bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[25]</value>
      <webElementGuid>7bc7b6c9-862d-476c-ae40-ddd572b88c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio5']</value>
      <webElementGuid>fc630678-f55f-45cf-a898-1fbc37e1d524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
