<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text8_text8</name>
   <tag></tag>
   <elementGuidId>e316b319-5eb4-44f1-a56e-d4d7e4c0aab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ffa6d3b-a294-4c10-acd3-9197b27d13f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b26a9e69-f14d-430e-8812-d6cfea4f9ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text8</value>
      <webElementGuid>62d8b9b7-10ae-4d1b-a406-2c61e7c29566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text8&quot;)</value>
      <webElementGuid>bf641f0e-87c4-4c50-bfd3-54d7d2e2f9fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text8']</value>
      <webElementGuid>f23cac8e-8d1c-4838-a804-baf2e6c3258c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>49fbafd4-d6c4-4434-b8a2-5e20b5b41b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text8']</value>
      <webElementGuid>b2dbd775-3d27-49eb-bb4e-76de22dd50d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
