<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox9_checkbox10</name>
   <tag></tag>
   <elementGuidId>b1087ab7-a4ea-43b7-94a8-94050acc8f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd1c2cf6-5bbc-4ee9-aa9f-949cd70e90f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8c2e71c5-7785-4763-8882-387849ab209d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox10</value>
      <webElementGuid>a779a876-9892-488e-b093-77499c3806f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox10</value>
      <webElementGuid>18d8dc04-cf67-410f-af99-ba302c45b4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox10&quot;)</value>
      <webElementGuid>82fed4f1-f65a-41a1-a966-82bf9f7333f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox10']</value>
      <webElementGuid>3c5e4367-8ed6-4505-973a-73c29fb238a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[20]</value>
      <webElementGuid>2e3bdeec-9f50-409d-a02d-5e0c3e18bc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox10']</value>
      <webElementGuid>90b00425-4f19-426d-9533-62cee88e7407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
