<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox7_checkbox8</name>
   <tag></tag>
   <elementGuidId>fa82d12b-fe53-4524-b89b-2f75b4bcbb91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30ca6c78-23e7-405a-9837-92fd1dbba90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c335541b-532a-4897-94d2-1d019fba9453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox8</value>
      <webElementGuid>c7dcb585-28e2-47e1-a663-85c6e69c2e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox8</value>
      <webElementGuid>8d5a8108-ea1f-465d-8abd-ad58ac0e0f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox8&quot;)</value>
      <webElementGuid>e0a23b38-dbb9-4080-b721-168de04e9623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox8']</value>
      <webElementGuid>239cd838-4c9d-47c5-a3e4-578237dea5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[18]</value>
      <webElementGuid>df9d1216-6f69-4e0a-9c22-c2016cfb13f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox8']</value>
      <webElementGuid>f597c667-8332-4400-9aad-d3961b406405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
