<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio8_radio9</name>
   <tag></tag>
   <elementGuidId>9c586418-8a99-4a5b-ab17-bb4d9a4d045f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91b07335-1dff-4aaf-9688-ecee4adab9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6952766a-828e-45bd-8a1a-6884963637a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio9</value>
      <webElementGuid>7c31dcc7-6171-4f38-9f42-a06413388a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio9</value>
      <webElementGuid>b7394003-a22e-45a2-b44a-8ffb78d44c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio9&quot;)</value>
      <webElementGuid>0a9bee8d-2966-4bd8-b0dd-338058662753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio9']</value>
      <webElementGuid>5e8413d0-f625-4b3b-a586-bb28b9888994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[29]</value>
      <webElementGuid>93ab4acf-c8a2-4230-913c-83e955a08b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio9']</value>
      <webElementGuid>f0b146d0-727f-44cb-aaaf-55bdce2633aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
